const items = [
  {
    id: 1,
    title: "Tafadzwa Mpofu",
    sport: "Rugby",
    motto: "I can, therefore I am",
    height: "173",
    weight: "82",
    location: "Norwich, United Kingdom",
    nationality: "South African",
    desc: "Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level. Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.",
    img: "/ambassadors/tino/tino8.jpeg",
    img1: "/ambassadors/tino/tino1.jpeg",
    img2: "/ambassadors/tino/tino2.jpeg",
    img3: "/ambassadors/tino/tino3.jpeg",
    img4: "/ambassadors/tino/tino4.jpeg",
    img5: "/ambassadors/tino/tino5.jpeg",
    img6: "/ambassadors/tino/tino6.jpeg",
    img7: "/ambassadors/tino/tino7.jpeg",
    img8: "/ambassadors/tino/tino8.jpeg",
    img9: "/ambassadors/tino/tino9.jpeg",
  },
  {
    id: 2,
    title: "Yassin Labukeni",
    sport: "Football",
    motto: "Live, Love, Laugh !",
    height: "177",
    weight: "87",
    location: "Leeds, United Kingdom",
    nationality: "Zimbabwean",
    desc: "Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level. Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level. Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level. Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level. Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level. Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level. Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level.",
    img: "/ambassadors/yassin/yassin.jpeg",
    img1: "/ambassadors/yassin/yassin1.jpeg",
    img2: "/ambassadors/yassin/yassin2.jpeg",
    img3: "/ambassadors/yassin/yassin3.jpeg",
    img4: "/ambassadors/yassin/yassin4.jpeg",
    img5: "/ambassadors/yassin/yassin5.jpeg",
    img6: "/ambassadors/yassin/yassin6.jpeg",
    img7: "/ambassadors/yassin/yassin7.jpeg",
    img8: "/ambassadors/yassin/yassin8.jpeg",
    img9: "/ambassadors/yassin/yassin9.jpeg",
  },
  {
    id: 3,
    title: "Tafadzwa Mpofu",
    sport: "Rugby",
    motto: "I can, therefore I am",
    height: "173",
    weight: "82",
    location: "Norwich, United Kingdom",
    nationality: "South African",
    desc: "Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level. Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.",
    img: "/ambassadors/tino/tino8.jpeg",
    img1: "/ambassadors/tino/tino1.jpeg",
    img2: "/ambassadors/tino/tino2.jpeg",
    img3: "/ambassadors/tino/tino3.jpeg",
    img4: "/ambassadors/tino/tino4.jpeg",
    img5: "/ambassadors/tino/tino5.jpeg",
    img6: "/ambassadors/tino/tino6.jpeg",
    img7: "/ambassadors/tino/tino7.jpeg",
    img8: "/ambassadors/tino/tino8.jpeg",
    img9: "/ambassadors/tino/tino9.jpeg",
  },
  {
    id: 4,
    title: "Yassin Labukeni",
    sport: "Football",
    motto: "Live, Love, Laugh !",
    height: "177",
    weight: "87",
    location: "Leeds, United Kingdom",
    nationality: "Zimbabwean",
    desc: "Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level. Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level. Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level. Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level. Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level. Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level. Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level.",
    img: "/ambassadors/yassin/yassin.jpeg",
    img1: "/ambassadors/yassin/yassin1.jpeg",
    img2: "/ambassadors/yassin/yassin2.jpeg",
    img3: "/ambassadors/yassin/yassin3.jpeg",
    img4: "/ambassadors/yassin/yassin4.jpeg",
    img5: "/ambassadors/yassin/yassin5.jpeg",
    img6: "/ambassadors/yassin/yassin6.jpeg",
    img7: "/ambassadors/yassin/yassin7.jpeg",
    img8: "/ambassadors/yassin/yassin8.jpeg",
    img9: "/ambassadors/yassin/yassin9.jpeg",
  },
  {
    id: 5,
    title: "Tafadzwa Mpofu",
    sport: "Rugby",
    motto: "I can, therefore I am",
    height: "173",
    weight: "82",
    location: "Norwich, United Kingdom",
    nationality: "South African",
    desc: "Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level. Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.",
    img: "/ambassadors/tino/tino8.jpeg",
    img1: "/ambassadors/tino/tino1.jpeg",
    img2: "/ambassadors/tino/tino2.jpeg",
    img3: "/ambassadors/tino/tino3.jpeg",
    img4: "/ambassadors/tino/tino4.jpeg",
    img5: "/ambassadors/tino/tino5.jpeg",
    img6: "/ambassadors/tino/tino6.jpeg",
    img7: "/ambassadors/tino/tino7.jpeg",
    img8: "/ambassadors/tino/tino8.jpeg",
    img9: "/ambassadors/tino/tino9.jpeg",
  },
  {
    id: 6,
    title: "Yassin Labukeni",
    sport: "Football",
    motto: "Live, Love, Laugh !",
    height: "177",
    weight: "87",
    location: "Leeds, United Kingdom",
    nationality: "Zimbabwean",
    desc: "Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level. Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level. Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level. Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level. Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level. Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level. Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level.",
    img: "/ambassadors/yassin/yassin.jpeg",
    img1: "/ambassadors/yassin/yassin1.jpeg",
    img2: "/ambassadors/yassin/yassin2.jpeg",
    img3: "/ambassadors/yassin/yassin3.jpeg",
    img4: "/ambassadors/yassin/yassin4.jpeg",
    img5: "/ambassadors/yassin/yassin5.jpeg",
    img6: "/ambassadors/yassin/yassin6.jpeg",
    img7: "/ambassadors/yassin/yassin7.jpeg",
    img8: "/ambassadors/yassin/yassin8.jpeg",
    img9: "/ambassadors/yassin/yassin9.jpeg",
  },
  {
    id: 7,
    title: "Tafadzwa Mpofu",
    sport: "Rugby",
    motto: "I can, therefore I am",
    height: "173",
    weight: "82",
    location: "Norwich, United Kingdom",
    nationality: "South African",
    desc: "Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level. Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.Tino is a rugby player at Norwich Rugby Club and he has been playing rugby for a few years. His dream is to play rugby at a professional level.",
    img: "/ambassadors/tino/tino8.jpeg",
    img1: "/ambassadors/tino/tino1.jpeg",
    img2: "/ambassadors/tino/tino2.jpeg",
    img3: "/ambassadors/tino/tino3.jpeg",
    img4: "/ambassadors/tino/tino4.jpeg",
    img5: "/ambassadors/tino/tino5.jpeg",
    img6: "/ambassadors/tino/tino6.jpeg",
    img7: "/ambassadors/tino/tino7.jpeg",
    img8: "/ambassadors/tino/tino8.jpeg",
    img9: "/ambassadors/tino/tino9.jpeg",
  },
  {
    id: 8,
    title: "Yassin Labukeni",
    sport: "Football",
    motto: "Live, Love, Laugh !",
    height: "177",
    weight: "87",
    location: "Leeds, United Kingdom",
    nationality: "Zimbabwean",
    desc: "Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level. Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level. Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level. Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level. Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level. Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level. Yassin is a football player at Leeds United F.C and he has been playing football since he was 5 years old. His dream is to play football at a professional level.",
    img: "/ambassadors/yassin/yassin.jpeg",
    img1: "/ambassadors/yassin/yassin1.jpeg",
    img2: "/ambassadors/yassin/yassin2.jpeg",
    img3: "/ambassadors/yassin/yassin3.jpeg",
    img4: "/ambassadors/yassin/yassin4.jpeg",
    img5: "/ambassadors/yassin/yassin5.jpeg",
    img6: "/ambassadors/yassin/yassin6.jpeg",
    img7: "/ambassadors/yassin/yassin7.jpeg",
    img8: "/ambassadors/yassin/yassin8.jpeg",
    img9: "/ambassadors/yassin/yassin9.jpeg",
  },
];

export function getData() {
  return items;
}

export function getDataById(id) {
  return items.find((data) => data.id == id);
}
